# This is a basic workflow that is manually triggered

name: Deploy Manual nosso Site

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      substituir:
        type: boolean
      regiao:
        description: 'Escolhe uma regiao'
        type: choice
        options:
          - PT
          - ES
          - UK
      ambiente:
        type: environment
      servidor:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Servidor de destino'
        # Default value if no value is explicitly provided
        default: '/var/www'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string
      pasta:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Pasta de destino'
        # Default value if no value is explicitly provided
        default: '/var/www'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  copia:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - uses: actions/checkout@v4
    
    - name: passo1
      run: echo "Hello ${{ inputs.servidor }}"
    - name: passo2
      run: |
        ls -all

      
